apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: '{{ .Values.werf.image.portfolio }}'
          workingDir: /app
          env:
            - name: BSCSCAN_API_KEY
              value: '{{ .Values.bscscan.apiKey }}'
            - name: MORALIS_APP_ID
              value: '{{ .Values.moralis.appId }}'
            - name: MORALIS_API_KEY
              value: '{{ .Values.moralis.apiKey }}'
            - name: MORALIS_SERVER_URL
              value: '{{ .Values.moralis.serverUrl }}'
          ports:
            - containerPort: 3001
              protocol: TCP
