apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.werf.image.app }}"
          workingDir: /app
          env:
            - name: TYPEORM_URL
              value: postgres://postgres:postgres@ekp-farms-postgresql:5432/ekp_farms
            - name: BSCSCAN_URL
              value: https://api.bscscan.com
            - name: BSCSCAN_API_KEY
              value: "{{ .Values.bscscan.apiKey }}"
            - name: BSC_PROVIDER_TYPE
              value: JsonRpc
            - name: BSC_PROVIDER_URL
              value: https://bsc-dataseed1.ninicoin.io/

          ports:
            - containerPort: 3001
              protocol: TCP
