apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: app
spec:
  tls:
    - hosts:
        - ekp-farms.k.earnkeeper.io
        - db-farms.k.earnkeeper.io
      secretName: ekp-farms-tls
  rules:
    - host: ekp-farms.k.earnkeeper.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3001
    - host: db-farms.k.earnkeeper.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nocodb
                port:
                  number: 8080
