loki-stack:
  grafana:
    enabled: true
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
postgresql:
  postgresqlPassword: postgres
  postgresqlDatabase: ekp_farms